### ISSUE TITLE
cannot find function `block_on` in the crate root

### ISSUE THREAD

**Issue by xorxsan** [ntex-rs/ntex#115] opened 2022-06-13 13:20 UTC
Hi,

I'm still having some issues when trying to compile the example app shown on the documentation: https://docs.rs/ntex/latest/ntex/web/index.html
```
use ntex::web;

async fn index(info: web::types::Path<(String, u32)>) -> String {
    format!("Hello {}! id:{}", info.0, info.1)
}

#[ntex::main]
async fn main() -> std::io::Result<()> {
    web::server(|| web::App::new().service(
        web::resource("/{name}/{id}/index.html").to(index))
    )
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

Cargo.toml:
```
[dependencies]
ntex = { version = "*", features = ["async-std"] }

```

And these are the errors I'm getting:
```
error[E0425]: cannot find function `block_on` in the crate root
  --> xxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.4\src\arbiter.rs:96:24
   |
96 |                 crate::block_on(async move {
   |                        ^^^^^^^^ not found in the crate root
   |
help: consider importing one of these items
   |
1  | use async_std::task::block_on;
   |
1  | use crate::asyncstd::block_on;

error[E0425]: cannot find function `spawn` in the crate root
  --> xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.4\src\arbiter.rs:98:28
   |
98 |                     crate::spawn(ArbiterController {
   |                            ^^^^^ not found in the crate root
   |
help: consider importing one of these items
   |
1  | use async_std::task::spawn;
   |
1  | use crate::arbiter::thread::spawn;
   |
1  | use crate::asyncstd::spawn;
   |
1  | use std::thread::spawn;
```
```
error[E0425]: cannot find function `block_on` in the crate root
   --> xxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.4\src\builder.rs:162:12
    |
162 |     crate::block_on(Box::pin(async move {
    |            ^^^^^^^^ not found in the crate root
    |
help: consider importing one of these items
    |
1   | use async_std::task::block_on;
    |
1   | use crate::asyncstd::block_on;
    |
error[E0425]: cannot find function `spawn` in the crate root
   --> xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.4\src\builder.rs:163:16
    |
163 |         crate::spawn(arb);
    |                ^^^^^ not found in the crate root
    |
help: consider importing one of these items
    |
1   | use async_std::task::spawn;
    |
1   | use crate::asyncstd::spawn;
    |
1   | use std::thread::spawn;
    |
```
Rust version on Windows 10 x64
```
~ $ rustc --version
rustc 1.61.0 (fe5b13d68 2022-05-18)
```
Thanks!

**Comment by xorxsan** [comment] 2022-06-13 16:36
It does.

**Comment by fafhrd91** [comment] 2022-06-13 16:48
ok, i will check

**Comment by leon3s** [comment] 2022-06-19 15:20
Hey @xorxsan is it fixed ?
I couldn't reproduce this bug

**Comment by xorxsan** [comment] 2022-06-29 10:14
Hi,

   sorry for the late response.

   I run a `cargo update` to update the packages, but I'm still experiencing the same issue, albeit with `ntex-rt` version `0.4.5` instead of `0.4.4`:
```
   Compiling ntex-rt v0.4.5
error[E0425]: cannot find function `block_on` in the crate root
  --> xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.5\src\arbiter.rs:96:24
   |
96 |                 crate::block_on(async move {
   |                        ^^^^^^^^ not found in the crate root
   |
help: consider importing one of these items
   |
1  | use async_std::task::block_on;
   |
1  | use crate::asyncstd::block_on;
   |

error[E0425]: cannot find function `spawn` in the crate root
  --> xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.5\src\arbiter.rs:98:28
   |
98 |                     crate::spawn(ArbiterController {
   |                            ^^^^^ not found in the crate root
   |
help: consider importing one of these items
   |
1  | use async_std::task::spawn;
   |
1  | use crate::arbiter::thread::spawn;
   |
1  | use crate::asyncstd::spawn;
   |
1  | use std::thread::spawn;
   |

error[E0425]: cannot find function `spawn` in the crate root
   --> xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.5\src\arbiter.rs:265:32
    |
265 |                         crate::spawn(fut);
    |                                ^^^^^ not found in the crate root
    |
help: consider importing one of these items
    |
1   | use async_std::task::spawn;
    |
1   | use crate::arbiter::thread::spawn;
    |
1   | use crate::asyncstd::spawn;
    |
1   | use std::thread::spawn;
    |

error[E0425]: cannot find function `block_on` in the crate root
   -->xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.5\src\builder.rs:162:12
    |
162 |     crate::block_on(Box::pin(async move {
    |            ^^^^^^^^ not found in the crate root
    |
help: consider importing one of these items
    |
1   | use async_std::task::block_on;
    |
1   | use crate::asyncstd::block_on;
    |

error[E0425]: cannot find function `spawn` in the crate root
   --> xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.5\src\builder.rs:163:16
    |
163 |         crate::spawn(arb);
    |                ^^^^^ not found in the crate root
    |
help: consider importing one of these items
    |
1   | use async_std::task::spawn;
    |
1   | use crate::asyncstd::spawn;
    |
1   | use std::thread::spawn;
    |

error[E0425]: cannot find function `spawn` in the crate root
   --> xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-rt-0.4.5\src\builder.rs:164:16
    |
164 |         crate::spawn(arb_controller);
    |                ^^^^^ not found in the crate root
    |
help: consider importing one of these items
    |
1   | use async_std::task::spawn;
    |
1   | use crate::asyncstd::spawn;
    |
1   | use std::thread::spawn;
    |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `ntex-rt` due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
```

I've tried to fix this by updating the code replacing `crate::spawn` and `crate::block_on` by `crate::asyncstd::spawn` and `crate::asyncstd::block_on` respectively, but then it fails compiling `ntex-util` `v0.1.17`:
```
   Compiling ntex-util v0.1.17
error[E0432]: unresolved import `ntex_rt::spawn`
  --> xxxxx\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\ntex-util-0.1.17\src/lib.rs:10:9
   |
10 | pub use ntex_rt::spawn;
   |         ^^^^^^^^^^^^^^ no `spawn` in the root
```

```
$ cargo --version
cargo 1.61.0 (a028ae42f 2022-04-29)
```
`Cargo.toml`:
```
[dependencies]
base64 = "0.13"
env_logger = "0.8"
log = "0.4"
ntex = { version = "*", features = ["async-std", "rustls"] }
serde = "*"
serde_json = "*"
uuid = { version = "*", features = ["v4"] }
```

**Comment by leon3s** [comment] 2022-06-29 17:49
@xorxsan i think i fixed the bug [there](https://github.com/ntex-rs/ntex/pull/122)
if you wanna update locally and test

**Comment by fafhrd91** [comment] 2022-07-01 04:37
fixed in master

**Closed by fafhrd91** 2022-07-01 04:37 UTC
