### ISSUE TITLE
Stopping `Server` does not release resources

### ISSUE THREAD

**Issue by khvzak** [ntex-rs/ntex#233] opened 2023-10-25 22:17 UTC
Found when writing tests for my app.

Example to reproduce:
```rust
for i in 0.. {
    println!("{i}");

    let srv = web::server(|| {
        web::App::new().default_service(web::to(|| async { web::HttpResponse::Ok() }))
    })
    .bind("127.0.0.1:8989")
    .unwrap()
    .workers(1)
    .stop_runtime()
    .disable_signals()
    .run();

    srv.stop(true).await;
}
```

Eventually program will terminate with error `Too many open files` (depending on limits of course).

If do non-graceful termination (`srv.stop(false).await`) program will shortly terminate with error `Address already in use`.
Tested on macOS.

PS I know about the [`TestServer`](https://docs.rs/ntex/latest/ntex/web/test/struct.TestServer.html) but it uses a random port which is not always desirable.

**Comment by fafhrd91** [comment] 2023-10-26 03:13
i will check

**Comment by fafhrd91** [comment] 2023-11-02 10:27
what OS do you use? I cannot reproduce on Mac

**Comment by khvzak** [comment] 2023-11-02 22:08
macOS 13.6 x86_64 (Intel Core i9 cpu)
ntex v0.7.7 (latest + `cargo update`)

```
$ ulimit -n 1024

$ cargo run
   ...
   Compiling ntex-rt v0.4.10
   Compiling ntex-util v0.3.3
   Compiling ntex-io v0.3.4
   Compiling ntex-tokio v0.3.0
   Compiling ntex-tls v0.3.1
   Compiling ntex-connect v0.3.2
   Compiling ntex-h2 v0.4.3
   Compiling ntex v0.7.7
   Compiling ntex-test v0.1.0 (/Users/a/Projects/ntex-test)
    Finished dev [unoptimized + debuginfo] target(s) in 18.56s
     Running `target/debug/ntex-test`
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
thread 'thread 'thread 'ntex-rt:worker:251ntex-rt:worker:248ntex-rt:worker:250' panicked at ' panicked at ' panicked at /Users/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.10/src/lib.rs/Users/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.10/src/lib.rs/Users/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.10/src/lib.rs:::175175175:::1414:
14:
called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }:
called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }
called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


thread 'ntex-rt:worker:252' panicked at /Users/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.10/src/lib.rs:175:thread '14ntex-rt:worker:253:
' panicked at called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }/Users/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.10/src/lib.rs
:175:14:
called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }
thread 'ntex-rt:worker:255' panicked at /Users/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.10/src/lib.rs:175:14:
called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }
thread 'ntex-rt:worker:254' panicked at /Users/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.10/src/lib.rs:175:14:
called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }
```

**Comment by khvzak** [comment] 2023-11-02 22:12
If try with `srv.stop(false).await;`

```
$ ulimit -n unlimited

$ cargo run
     Running `target/debug/ntex-test`

0
...
149
150
thread 'main' panicked at src/main.rs:12:10:
called `Result::unwrap()` on an `Err` value: Os { code: 48, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
```

**Comment by fafhrd91** [comment] 2023-11-03 00:51
could you create runnable example

**Comment by khvzak** [comment] 2023-11-03 09:26
Done, the repo https://github.com/khvzak/ntex-233
Simply running `cargo run` triggers panic on linux and mac

**Comment by fafhrd91** [comment] 2023-11-06 07:17
fixed in master

**Closed by fafhrd91** 2023-11-06 07:17 UTC
